### ISSUE TITLE
Please add a LICENSE file

### ISSUE THREAD

**Issue by JJ** [pobox/Ix#105]
And, while you're at it, a README.md or .pod would help too :-)

**Comment by rjbs** [comment]
Hi, @JJ!  Out of curiosity, what led you here? :)

I've added a README — why not?  I also added a license.  It's possible we'll change the license (to same-as-Perl-5 or BSD?) at some point, but GPLv2 seemed like a safe choice for this work in progress, especially while all the contributors are staff and we can relicense freely!

**Comment by JJ** [comment]
Some post in some blog? I really don't remember now. Maybe in Twitter. It's
a great job, but I'm really picky about this kind of things :-)
